### ISSUE TITLE
Can we add origin to description?

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-fishes#5]
Do we have "vagrant", "introduced" info for fishes? @qgroom @timadriaens

**Comment by qgroom** [comment]
I've no idea, though it would obviously be quite important.
Quentin



Dr. Quentin Groom
(Botany and Information Technology)

Botanic Garden Meise
Domein van Bouchout
B-1860 Meise
Belgium

ORCID: 0000-0002-0596-5376 <http://orcid.org/0000-0002-0596-5376>

Landline; +32 (0) 226 009 20 ext. 364
FAX:      +32 (0) 226 009 45

E-mail:     quentin.groom@plantentuinmeise.be
Skype name: qgroom
Website:    www.botanicgarden.be

**Comment by timadriaens** [comment]
Yes we have that see [Hugo's paper](http://onlinelibrary.wiley.com/doi/10.1111/j.1095-8649.2007.01679.x/epdf), see table 1

The pathways can easily be mapped to the CBD standard I think although they are a mixture of category (e.g. unintentional) and subcategory 

AQ, aquaculture; (escape - aquaculture)
BW, ballast water; (stowaway -Ship/boat ballast water) 
AM, active migration; (unaided)
OR, ornamental; (escape - Pet/aquarium/terrarium species (including live food for such species), although this could in many cases also be "release - Landscape/flora/fauna “improvement” in the wild" 
AN, angling or bait fish; (escape - Live food and live bait)
BC, biological control; (release - biocontrol)
UN, unintentional; 

Invasion status:
A, acclimatized; N, naturalized; A*, acclimatized only in restricted areas at cooling water discharges of power plants)

Looking at the species, N can be considered **established**
A & A* can also be considered **established**, even if in secluded warmer water of power plants (cf nile tilapia) → some spp can only maintain populations due to human intervention

**Comment by peterdesmet** [comment]
So all species should be considered "introduced" using [this **origin** vocab](https://github.com/trias-project/vocab/blob/master/vocabulary/origin/origin.tsv)?

**Comment by qgroom** [comment]
Probably
Q



Dr. Quentin Groom
(Botany and Information Technology)

Botanic Garden Meise
Domein van Bouchout
B-1860 Meise
Belgium

ORCID: 0000-0002-0596-5376 <http://orcid.org/0000-0002-0596-5376>

Landline; +32 (0) 226 009 20 ext. 364
FAX:      +32 (0) 226 009 45

E-mail:     quentin.groom@plantentuinmeise.be
Skype name: qgroom
Website:    www.botanicgarden.be
