### ISSUE TITLE
Established vs naturalized

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-fishes#6]
I remember from the last meeting that all fishes were all "established", but right now "invasion stage" information is based on "raw_status", with:

|abbreviation |full name                                                                         |mapping       |
|:------------|:---------------------------------------------------------------------------------|:-------------|
|A            |acclimatized                                                                      |established   |  
|N            |naturalized                                                                       |naturalized|
|A*           |acclimatized only in restricted areas at cooling water discharges of power plants |established   |

Is this correct @timadriaens?

**Comment by timadriaens** [comment]
yes, I think you can put all of them down as established

**Comment by peterdesmet** [comment]
Ok, then we won't use the values in the spreadsheet. @timadriaens can you give a 2 sentence reasoning why all should be considered established, so we can add this to the Rmd documentation?

**Comment by LienReyserhove** [comment]
I integrated the following information in the Rmd documentation: 

For the TrIAS project, we decided to use the unified framework for biological invasions of [Blackburn et al. 2011](http://doc.rero.ch/record/24725/files/bach_puf.pdf), but we discard the terms `naturalized`(because often, there's no sensible criterium to distinguish between casual/naturalised of naturalised/established), and `invasive` (this is a label that should only be put on a species after risk assessment). Thus, here, we conider all species as `established`.

see [this comment](https://github.com/trias-project/alien-plants-belgium/issues/52#issuecomment-355976672) by @timadriaens
